### ISSUE TITLE
Paid training / workshops?

### ISSUE THREAD

**Issue by zimbatm** [nixcon/2023.nixcon.org#7]
We had a request last year to run a training workshop. What would be the conditions?

I can see two possible variations:

1. The workshop is for-profit. It happens outside of the venue, potentially a day before. In that case, NixCon could advertise its existence.
2. The workshop is part of the conference. In that case, it would be included in the price of the ticket. We would reserve a training room. The presenter would be free to advertise their course outside of the conference.

Maybe some other proposals?

**Comment by zimbatm** [comment]
@spacecookie are you interested in trying this again this year? If we get the conversation started now, it's more likely to happen.

**Comment by tfc** [comment]
Hi! I'm interested in doing this as i have a battle-tested/newbie-tested training course ready by then. One or the other or both variants? It surely depends on the conditions etc. - can we meet online and discuss details?

**Comment by spacekookie** [comment]
Hi!

Yes, I'd be very interested in giving a training. I've been teaching with https://github.com/spacekookie/learning-nix maybe 4 or 5 times now, and I can also adjust the material to have either a beginner or intermediary focus.

As a middle-ground between a paid workshop and a free one, the trainings could be part of the conference, and teachers get their travel + hotels paid for, similar to other speakers (I hope :sweat_smile:)

**Comment by tfc** [comment]
It seems like regarding payment and org, there are multiple possibilities:

- training is part of the conference and free/included in the ticket/an add-on ticket
  - hopefully travel + hotel is then paid for the trainers, maybe also time&materials
- training is near to the conference regarding time and location, but extra
  - trainers organize this themselves, nixcon team helps advertizing

Given we are two trainers who would like to participate, i think there is no problem because i am sure there are enough guests from the rapidly growing community to completely fill two course rooms.
We do however have multiple options here, which can both be applied to both variants (included in con, separate to con):

- a.) simply provide two trainings in different rooms/locations, same time
- b.) provide two differently scoped trainings at same location, but different times

Looking at it from the trainer perspective:

- a.)
  - I feel like this would make it easier for the trainers to provide the best experience for their guests because they can use their battle-tested training material as-is
  - It becomes a little competition, everyone wants go get their room filled, but maybe it's ok because there might be so many people so we can evenly distribute
- b.)
  - feels like a little bit of a gamble to choose a topic and then end up having only a few guests while the other trainer's training is full because the other topic turned out to catch more people
  - maybe we trainers have natural favorite topics that are perfectly distinct so everyone concentrate on what they do best

Any opinions on that from @spacekookie and the org team?

**Comment by zimbatm** [comment]
Regarding travel + hotels, this is not something that has been on the table before. Historically the conference has existed to regroup hackers, and the spirit has always been scrappy/open-source. The speakers and organizers would get free tickets, and the conference budget (sponsor+ticket) would cover the location, food and swag. People would be motivated enough to organize everything for free, and come and give a talk, which is pretty amazing. Ideally, I would like to be able to keep that spirit.

At the same time, it makes sense to adjust those policies to the size of the community and conference. If we get more sponsorship this year, we could create a budget for travel, with criteria based on travel distance. To be discussed..

**Comment by lf-** [comment]
> motivated enough to organize everything for free, and come and give a talk

The trouble is that not everyone is so fortunate as to be able to travel to a conference and speak even if motivated.

There was an unfortunate lack of diversity in the speaker lineup last year. I was the only woman speaker with a full length slot. Had my then-employer not paid for travel and hotels I would likely not have been able to go if I happened to be on a school term rather than working. Obviously being able to offer funding for travel is limited based on sponsorships and this may be something to look into in the future when NixCon is larger.

I think that a particularly good example of how to handle speaker funding is !!Con (when they were running in person; when they were online, they paid for good microphones and webcams in addition to honoraria): https://bangbangcon.com/2019/give-a-talk.html

**Comment by andir** [comment]
We had a conversation about this and the following is the balance that we could agree on:
  * We are comfortable providing "payment" in the form of Bronze sponsorship tier. This includes the free ticket that comes with the sponsorship tier and the exposure on the event (logos, stickers, ... ).
  * We aren't going to pay for travel or hotel expenses for trainers.
  * We are making a room available for the training. Training schedules have to be negotiated.
  * Workshop proposals can be submitted via the regular CfP interface.

**Comment by zimbatm** [comment]
The next step for you would be to submit your workshop proposal to: https://talks.nixcon.org/nixcon-2023/cfp

Thanks for your patience while we figure out how to best handle workshops.
